data_path: "/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg"  # Combine Data with parent path
yolo_train_path: '/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg_yolo/train' # train path
yolo_val_path: '/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg_yolo/val' # validation path
yolo_test_path: '/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg_yolo/test' # validation path
yaml_path: '/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg_yolo/data.yaml'
seed: 2024
train_valid_test_ratio: [0.7, 0.2, 0.1] # 7:2:1