model: "yolov8.pt" # importent * model select 
OUTPUT_PATH: ""

seed: 2024
yaml_path: "/Users/kwon/Workspace/Python/cell-detection-yolo/Data/nuinsseg_yolo/data.yaml"
epochs: 100
imgsz: 512
batch: 8
workers: 4